### ISSUE TITLE
textlint parse error occurred.

### ISSUE THREAD

**Issue by sifue** [textlint/textlint#104]
a markdown file contains follow sentences.

```md
<pre><code class="lang-diff">   res.end('ページがみつかりません');
 }

+function handleBadRequest(req, res) {
+  res.writeHead(400, {
+    'Content-Type': 'text/plain',
+    'charset': 'utf-8'
+  });
+  res.end('未対応のメソッドです');
+}
+
 module.exports = {
   handleLogout: handleLogout,
-  handleNotFound: handleNotFound
+  handleNotFound: handleNotFound,
+  handleBadRequest: handleBadRequest
 };</code></pre>
```

this error occurred.
```
/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:641
    var character = value.charAt(index);
                         ^

TypeError: Cannot read property 'charAt' of undefined
    at getIndent (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:641:26)
    at Parser.renderNormalListItem (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:3539:16)
    at Parser.renderListItem (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:3582:50)
    at Parser.tokenizeList (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:1902:31)
    at Parser.tokenize [as tokenizeBlock] (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:5996:28)
    at Parser.renderBlock (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:3810:41)
    at Parser.parse (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/remark/lib/parse.js:5471:17)
    at Function.parse (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/unified/index.js:184:69)
    at parse (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/markdown-to-ast/lib/markdown/markdown-parser.js:30:22)
    at TextlintCore.lintMarkdown (/Users/soichiro_yoshimura/workspace/xxxxxxxx/node_modules/textlint/lib/textlint-core.js:141:23)
```

**Comment by azu** [comment]
@sifue Thanks for report!

It seem a bug on [remark](https://github.com/wooorm/remark "remark") which is a markdown parser.
Please let me know about version of remark.

```
npm ls | grep remark
```

**Comment by azu** [comment]
I file issue to remark.

- https://github.com/wooorm/remark/issues/137

**Comment by sifue** [comment]
thank you for your information.
I use
```
│ │ └─┬ remark@3.2.0
```
I'll try version up. Thanks.
