### ISSUE TITLE
Fixed result is not shown when both `--dry-run` and `--stdin` are given

### ISSUE THREAD

**Issue by kg8m** [textlint/textlint#1091]
Hi. Thanks a lot for developing this great tool. textlint really helps my text-editing life.

* * *

**What version of textlint are you using?**
```sh
$ npx --no-install textlint -v
v13.3.0
```

**What file type (Markdown, plain text, etc.) are you using?**
Markdown (and so on)

**What did you do? Please include the actual source code causing the issue.**
Run the cli textlint as follows:

```sh
$ echo 'jquery' | textlint --fix --dry-run --stdin --stdin-filename test.md --format fixed-result --rule 'textlint-rule-terminology'
```

**What did you expect to happen?**
We see `jQuery\n`.

**What actually happened? Please include the actual, raw output from textlint.**

We see no output.

For your information, the output is shown if removing `--dry-run` option.

I think fixing works properly but its output isn't shown. Here is output with `--debug` option:

```sh
$ echo 'jquery' | textlint --fix --dry-run --stdin --stdin-filename test.md --format fixed-result --rule 'textlint-rule-terminology' --debug
  textlint:cli cliOptions: {"fix":true,"dryRun":true,"stdin":true,"stdinFilename":"test.md","format":"fixed-result","rule":["textlint-rule-terminology"],"debug":true,"ignorePath":"${PWD}/.textlintignore","init":false,"color":true,"quiet":false,"textlintrc":true,"cache":false,"cacheLocation":"${PWD}/.textlintcache","_":[]} +0ms
  textlint:cli textlint --version: 13.3.0 +0ms
  textlint:cli Running on text, stdin-filename: test.md +0ms
  textlint:cli cliDescriptor: {"rule":[{"id":"terminology","options":{}}],"filterRule":[],"plugin":[]} +9ms
  textlint:loader:TextlintrcLoader loadTextlintrc failed: { ok: false, error: { message: 'textlint config is not found', errors: [ Error: textlint config is not found  textlint require .textlintrc config file. The config file define the use of rules. at loadRawConfig (${NODEJS_DIR}/lib/node_modules/textlint/node_modules/@textlint/config-loader/lib/src/config-loader.js:120:25) at loadConfig (${NODEJS_DIR}/lib/node_modules/textlint/node_modules/@textlint/config-loader/lib/src/config-loader.js:71:55) at loadTextlintrc (${NODEJS_DIR}/lib/node_modules/textlint/lib/src/loader/TextlintrcLoader.js:36:57) at loadDescriptor (${NODEJS_DIR}/lib/node_modules/textlint/lib/src/cli.js:27:55) at async Object.executeWithOptions (${NODEJS_DIR}/lib/node_modules/textlint/lib/src/cli.js:111:28) ] } } +0ms
  textlint:cli textlintrcDescriptor: {"rule":[],"filterRule":[],"plugin":[{"id":"@textlint/textlint-plugin-text","options":{}},{"id":"@textlint/textlint-plugin-markdown","options":{}}]} +2ms
  textlint:cli mergedDescriptor: {"rule":[{"id":"terminology","options":{}}],"filterRule":[],"plugin":[{"id":"@textlint/textlint-plugin-text","options":{}},{"id":"@textlint/textlint-plugin-markdown","options":{}}]} +0ms
  textlint:kernel used plugin "@textlint/textlint-plugin-markdown" +0ms
  textlint:kernel process file test.md +3ms
  textlint:TextLintCoreTask fixerRule TextlintFixableRuleDescriptor {
  textlintKernelRule: {
    type: 'Rule',
    ruleId: 'terminology',
    rule: {
      linter: [Function: reporter],
      fixer: [Function: reporter],
      test: [Object]
    },
    options: true,
    filePath: '${NODEJS_DIR}/lib/node_modules/textlint-rule-terminology/index.js',
    moduleName: 'textlint-rule-terminology'
  }
} +0ms
  textlint:TextLintCoreTask filterRules TextlintFilterRuleDescriptors { ruleDescriptorList: [] } +2ms
  textlint:core-task terminology report {"message":"Incorrect usage of the term: “jquery”, use “jQuery” instead","index":0,"fix":{"range":[0,6],"text":"jQuery","isAbsolute":false}} +0ms
  textlint:source-code-fixer Applying fixes +0ms
  textlint:source-code-fixer Found fixes to apply +0ms
  textlint:fixer-processor Finish Processing: test.md +0ms
  textlint:fixer-processor applyingMessages: 1 +0ms
  textlint:fixer-processor remainingMessages: 0 +0ms
  textlint:cli fix results: [{"filePath":"test.md","output":"jQuery\n","messages":[{"type":"lint","ruleId":"terminology","message":"Incorrect usage of the term: “jquery”, use “jQuery” instead","index":0,"line":1,"column":1,"range":[0,1],"loc":{"start":{"line":1,"column":1},"end":{"line":1,"column":2}},"severity":2,"fix":{"range":[0,6],"text":"jQuery"}}],"applyingMessages":[{"type":"lint","ruleId":"terminology","message":"Incorrect usage of the term: “jquery”, use “jQuery” instead","index":0,"line":1,"column":1,"range":[0,1],"loc":{"start":{"line":1,"column":1},"end":{"line":1,"column":2}},"severity":2,"fix":{"range":[0,6],"text":"jquery"}}],"remainingMessages":[]}] +14ms
  textlint:textfix-formatter formatterName: fixed-result +0ms
  textlint:textfix-formatter use formatter: ${NODEJS_DIR}/lib/node_modules/textlint/node_modules/@textlint/fixer-formatter/lib/src/formatters/fixed-result.js +1ms
  textlint:cli Enable dry-run mode +1ms
```

* * *

Best regards.

**Comment by Sean0628** [comment]
We should call `printResults(output, cliOptions)` before returning the promise?
refs https://github.com/textlint/textlint/pull/1011/files#diff-ed8fbb3758d3fe109515c27e81f62365afe67f4bfa74a6287b9e46e7ac3ced44L98

**Comment by azu** [comment]
It looks like regression on v13+.

@Sean0628 Yes, Probably you are correct.

**Comment by Sean0628** [comment]
Thanks.
> Can you create a PR?

Okay. Will take a look.

**Comment by Sean0628** [comment]
Do you think I better add a test case for `--stdin` as well? It seems like this bug has noting to do with that option.

**Comment by kg8m** [comment]
@Sean0628 @azu 
Thank you so much!

**Comment by azu** [comment]
Fixed in https://github.com/textlint/textlint/releases/tag/v13.3.1
