### ISSUE TITLE
[Documentation] Better linter.lintText documentation/Upgrade Guide

### ISSUE THREAD

**Issue by davmillar** [textlint/textlint#1423]
**What version of textlint are you using?**
13.x/14.2.0

**What file type (Markdown, plain text, etc.) are you using?**
plaintext/string

**What did you do? Please include the actual source code causing the issue.**

I am migrating from v13 to v14 and am trying to replace the following code:

```js
return engine.executeOnText(ruleText).then(function(results) {
...
```

I have tried changing that to the following:

```js
return await linter.lintText(ruleText).then(function(results) {
...
```

**What did you expect to happen?**

I expected similar behavior as before, or guidance from the error messages to resolve the issue.

**What actually happened? Please include the actual, raw output from textlint.**

Initially I received the following:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.extname (node:path:1416:5)
    at Object.lintText (/home/millard/dev/psi/source/juno/node_modules/textlint/lib/src/createLinter.js:94:37)
    at lintRule (file:///home/millard/dev/psi/source/juno/bin/spellcheck.mjs:27:25)
    at main (file:///home/millard/dev/psi/source/juno/bin/spellcheck.mjs:63:23)
    at file:///home/millard/dev/psi/source/juno/bin/spellcheck.mjs:79:1 {
  code: 'ERR_INVALID_ARG_TYPE'
```

I was unsure what the path argument should contain because the way we're using textlint is separated from the way we store the text. I tried passing an empty string, and instead got this:

```
Error: Not found available plugin for 
    at TextlintKernel._parallelProcess (/home/millard/dev/psi/source/juno/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:124:19)
    at /home/millard/dev/psi/source/juno/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:84:25
```

I'm unsure how to proceed and am unable to get the search box on the textlint website to work, and cannot find adequate documentation to proceed. If possible, I would appreciate:

1. Guidance on how I should proceed
2. Direction to the API documentation if it already exists. If it doesn't, I would be happy to work with a developer familiar with textlint to write some.
3. Possibly an upgrade/migration guide for moving off of TextLintEngine to the new APIs -- again, happy to help write it if it doesn't exist already.

Thank you developers/maintainers for your hard work and let me know if I can help at all as well. :)

**Comment by azu** [comment]
`linter.lintText(text, filePath)` 
`filePath` is used for detecting what file type.
If you want to lint text as Markdown, please `linter.lintText(text, "dummy.md")`.


I agree that We need to update documents.

**Comment by davmillar** [comment]
Thanks a ton, that worked exactly how I needed.
