### ISSUE TITLE
No globs support

### ISSUE THREAD

**Issue by sapegin** [textlint/textlint#261]
As mentioned in the Readme:

> Allow to use glob as a target.
> 
> Please note that you have to quote your parameter as follows:
> 
> ```sh
> $ textlint "docs/**"
> ```

It doesn’t work and I don’t see a glob expansion anywhere in the code.

```
❯ textlint "source/en/all/*.md"
✖ Error
ENOENT: no such file or directory, stat 'source/en/all/*.md'

✖ Stack trace
Error: ENOENT: no such file or directory, stat 'source/en/all/*.md'
    at Object.fs.statSync (fs.js:907:18)
    at walk (/usr/local/lib/node_modules/textlint/lib/util/traverse.js:21:19)
    at /usr/local/lib/node_modules/textlint/lib/util/traverse.js:76:9
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/textlint/lib/util/traverse.js:75:11)
    at findFiles (/usr/local/lib/node_modules/textlint/lib/util/find-util.js:18:5)
    at TextLintEngineCore.executeOnFiles (/usr/local/lib/node_modules/textlint/lib/engine/textlint-engine-core.js:281:55)
    at Object.executeWithOptions (/usr/local/lib/node_modules/textlint/lib/cli.js:171:96)
    at Object.execute (/usr/local/lib/node_modules/textlint/lib/cli.js:115:25)
    at /usr/local/lib/node_modules/textlint/bin/textlint.js:33:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

It however work without quotes but I’m afraid that’s because of my Zsh and might not work on other platforms.

```
❯ textlint source/en/all/*.md

/Users/sapegin/Dropbox/Projects/_Repos/blog.sapegin.me/source/en/all/bower.md
   16:26   ✓ error  Incorrect usage of the term: “websites”, use “sites” instead             terminology
...
```

**Comment by azu** [comment]
Good catch. It is documentation bug.
(or missing feature)

**Comment by azu** [comment]
We will release this feature #264 at tomorrow.

**Comment by azu** [comment]
Release https://github.com/textlint/textlint/releases/tag/v7.3.0
It support glob pattern.

@sapegin Please check v7.3.0,  this issue should be fixed.
