### ISSUE TITLE
run pretter-error formatter on memory

### ISSUE THREAD

**Issue by odanado** [textlint/textlint#550]
**What version of textlint are you using?**
node: v8.11.3
textlint: v11.0.0

**What file type (Markdown, plain text, etc.) are you using?**
Markdown

**What did you do? Please include the actual source code causing the issue.**
```node:index.js
const path = require('path')
const { TextLintEngine } = require("textlint");
const { createFormatter } = require("@textlint/linter-formatter");

(async () => {
    const engine = new TextLintEngine({
        configFile: path.resolve(__dirname, ".textlintrc"),
    });

    const document = `
こんにちは!
こんばんは!
    `

    const formatter = createFormatter({
        formatterName: "pretty-error"
    });

    const result = await engine.executeOnText(document, '.md');

    const { messages } = result[0];
    const output = formatter([{ messages }]);
    console.log(output);
})()
```

**What did you expect to happen?**
show a formatted message

**What actually happened? Please include the actual, raw output from textlint.**

```bash
$ node issue.js
(node:59097) UnhandledPromiseRejectionWarning: TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /Users/user/source/javascript/textlint-sandbox/node_modules/@textlint/linter-formatter/lib/linter-formatter/src/format
ters/pretty-error.js:116:34
    at Array.forEach (<anonymous>)
    at formatter (/Users/user/source/javascript/textlint-sandbox/node_modules/@textlint/linter-formatter/lib/linter-formatter/src/formatters/pretty-error.js:115:13)
    at /Users/user/source/javascript/textlint-sandbox/node_modules/@textlint/linter-formatter/lib/linter-formatter/src/index.js:42:16
    at /Users/user/source/javascript/textlint-sandbox/issue.js:22:20
    at <anonymous>
(node:59097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Because it depends on `fs` .
https://github.com/textlint/textlint/blob/5b4d859ef5d3e95f61e07086b18318fe7b574fa0/packages/%40textlint/linter-formatter/src/formatters/pretty-error.ts#L132

**Comment by azu** [comment]
Thanks for report.
[TextLintResult](https://github.com/textlint/textlint/blob/master/docs/formatter.md) does not have source code yet.
So, `pretty-error` has depened on `filePath`.

ESLint's message have `source` property.
If we want to resolve this issue, we need to add `source` property to `TextLintResult`.

## Pros

- Make `pretty-error` in-memory implementation

## Cons

- Make `TextLintResult` size large

📝 ESLint's implementaion

> source: The source code for the given file. This property is omitted if this file has no errors/warnings or if the output property is present.

**Comment by azu** [comment]
Yes! Welcome to Pull Request.
