### ISSUE TITLE
doesn't work correctly with `--stdin` and `pretty-error`

### ISSUE THREAD

**Issue by zakkie** [textlint/textlint#739]
unhandled exception occurred when `--stdin` and `pretty-error`:

```
$ textlint --rule no-todo --stdin --stdin-filename foo.md -f pretty-error < /tmp/foo.md
✖ Error
ENOENT: no such file or directory, open '<markdown>'

✖ Stack trace
Error: ENOENT: no such file or directory, open '<markdown>'
    at Object.openSync (node:fs:490:3)
    at Object.readFileSync (node:fs:391:35)
    at /usr/local/lib/node_modules/textlint/node_modules/@textlint/linter-formatter/lib/formatters/pretty-error.js:116:34
    at Array.forEach (<anonymous>)
    at formatter (/usr/local/lib/node_modules/textlint/node_modules/@textlint/linter-formatter/lib/formatters/pretty-error.js:115:13)
    at /usr/local/lib/node_modules/textlint/node_modules/@textlint/linter-formatter/lib/index.js:43:16
    at TextLintEngine.AbstractTextLintEngine.formatResults (/usr/local/lib/node_modules/textlint/lib/engine/textlint-engine-core.js:252:16)
    at /usr/local/lib/node_modules/textlint/lib/cli.js:211:37
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

$ cat /tmp/foo.md
- [ ] foo
- bar

$ textlint -v
v11.8.1
$ node -v
v15.6.0
```

**It works fine if specified the file path directly:**

```
$ textlint --rule no-todo /tmp/foo.md -f pretty-error < /tmp/foo.md
no-todo: Found TODO: '- [ ] foo'
/tmp/foo.md:1:3
         v
    0.
    1. - [ ] foo
    2. - bar
         ^

✖ 1 problem (1 error, 0 warnings)
```

**Also it works fine if without `-f pretty-error` option:**

```
$ textlint --rule no-todo --stdin --stdin-filename foo.md  < /tmp/foo.md

<markdown>
  1:3  error  Found TODO: '- [ ] foo'  no-todo

✖ 1 problem (1 error, 0 warnings)
```

**Comment by azu** [comment]
Thanks for the report.

It is an expected error because pretty-error read file content using `filePath` of `TextlintResult`.

https://github.com/textlint/textlint/blob/7dffafadd3ef613c6868b7be07703b1da792ec6f/packages/%40textlint/linter-formatter/src/formatters/pretty-error.ts#L127

Current `TextlintResult` does not include actual file content.

https://github.com/textlint/textlint/blob/0e4c8283745e34950c1b036c0faabb2a769b5e9d/packages/%40textlint/types/src/Message/TextlintResult.ts#L7-L33

So, It is a current limitation.

We have two options for improving this error.

1. Improve error message(show a message that it is the limitation)
2. Fix to work pretty-error with `--stdin`

2 is ideal, but It means that add file content to `TextlintResult` like [ESLint's source](https://eslint.org/docs/developer-guide/working-with-custom-formatters).
I concerned that TextlintResult output is going to be bigger.

I have not an actual use case that adds file content to `TextlintResult`, so I did not implement `-f pretty-error` with `--stdion`.

If there is another use-case, I'm ok that implement 2 of the options.
