### ISSUE TITLE
Loading custom formatter via file (not package)

### ISSUE THREAD

**Issue by takenspc** [textlint/textlint#941]
**What version of textlint are you using?**

12.2.3

**What file type (Markdown, plain text, etc.) are you using?**

Markdown

**What did you do? Please include the actual source code causing the issue.**

It is convenient that textlint can load custom formatter via file.

```sh
textlint -f custom-formatter.js **/*.md
```

Source Code: https://github.com/takenspc/junit-reports/tree/textlint

**What did you expect to happen?**

texlint loads the formatter.

**What actually happened? Please include the actual, raw output from textlint.**

textlint failed to load the formatter.

Log of GitHub Actions: https://github.com/takenspc/junit-reports/actions/runs/3493635216/jobs/5848666329

```
Error
Could not find formatter custom-formatter.js
Error: Cannot find module 'custom-formatter.js'
Require stack:
- /home/runner/work/junit-reports/junit-reports/node_modules/@textlint/linter-formatter/lib/src/index.js
- /home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/options.js
- /home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/cli.js
- /home/runner/work/junit-reports/junit-reports/node_modules/textlint/bin/textlint.js

Stack trace
Error: Could not find formatter custom-formatter.js
Error: Cannot find module 'custom-formatter.js'
Require stack:
- /home/runner/work/junit-reports/junit-reports/node_modules/@textlint/linter-formatter/lib/src/index.js
- /home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/options.js
- /home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/cli.js
- /home/runner/work/junit-reports/junit-reports/node_modules/textlint/bin/textlint.js
    at createFormatter (/home/runner/work/junit-reports/junit-reports/node_modules/@textlint/linter-formatter/lib/src/index.js:40:15)
    at TextLintEngine.onFormat (/home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/textlint-engine.js:48:59)
    at TextLintEngine.formatResults (/home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/engine/textlint-engine-core.js:239:32)
    at /home/runner/work/junit-reports/junit-reports/node_modules/textlint/lib/src/cli.js:221:39
```

## Related codes

https://github.com/textlint/textlint/blob/752d866a6d38c32c8984e45e977511d8f418adce/packages/%40textlint/linter-formatter/src/index.ts#L24

```js
if (fs.existsSync(formatterName)) {
  formatterPath = formatterName;
}
// snip
try {
  formatter = moduleInterop(require(formatterPath));
} catch (ex) {
  throw new Error(`Could not find formatter ${formatterName}
${ex}`);
}
```

In most cases, [`fs.existsSync` resolves relative paths using `process.cwd()`](https://nodejs.org/api/fs.html#string-paths) while [`require()` resolves relative paths using `__dirname`](https://nodejs.org/api/modules.html#requireid).

That is, existence of a relative path resolved using `process.cwd()` does not guarantee the relative path can be `require`d.

One of possible solutions is changing

```js
if (fs.existsSync(formatterName)) {
  formatterPath = formatterName;
```

to 

```js
if (fs.existsSync(path.resolve(__dirname, formatterName))) {
  formatterPath = path.resolve(__dirname, formatterName);
```

**Comment by azu** [comment]
Can you try next?

```
textlint -f ./custom-formatter.js **/*.md
```
